### ISSUE TITLE
V5 Smart Retry Doesn't Seem to Work with new ListFilter Pagination

### ISSUE THREAD

**Issue by Powellze** [nozzlegear/ShopifySharp#472] opened 2020-03-04 09:51 UTC
on the new list sync pagination i'm receiving 500 internal server errors, which aren't caught by Smart Retry.

![image](https://user-images.githubusercontent.com/34938196/75866712-5efd7780-5dfd-11ea-9628-93b41e0e75dc.png)

![image](https://user-images.githubusercontent.com/34938196/75866751-72a8de00-5dfd-11ea-98d2-9333a6639937.png)

![image](https://user-images.githubusercontent.com/34938196/75866961-c3203b80-5dfd-11ea-8d20-063e74ea2a59.png)

**Comment by clement911** [comment] 2020-03-04 10:02
The `SmartRetryExecutionPolicy` only retries on 429 and not 500.
This is not new.

500 means Shopify had an error internally.
Can you share the url it's failing on?

**Comment by Powellze** [comment] 2020-03-04 11:20
@clement911 
Yeah we noticed that, we've had to wrap it in a General Exception at the moment.
https://xxxxx.myshopify.com/admin/api/2019-10/orders.json?page_info=eyJkaXJlY3Rpb24iOiJuZXh0Iiwic3RhdHVzIjoiYW55IiwiZmluYW5jaWFsX3N0YXR1cyI6InBhaWQiLCJjcmVhdGVkX2F0X21pbiI6IjIwMTgtMDktMDQgMDg6MzU6NTggVVRDIiwiY3JlYXRlZF9hdF9tYXgiOiIyMDIwLTAzLTA0IDA5OjM2OjAzIFVUQyIsImxhc3RfaWQiOjE5ODQzOTY3NTUwODMsImxhc3RfdmFsdWUiOiIyMDIwLTAxLTE3IDAxOjQ3OjE5In0&limit=100&fields=id%2Ccustomer%2Ccreated_at%2Corder_number%2Cfinancial_status%2Cline_items

the page info contains:
{"direction":"next","status":"any","financial_status":"paid","created_at_min":"2018-09-04 08:35:58 UTC","created_at_max":"2020-03-04 09:36:03 UTC","last_id":1984396755083,"last_value":"2020-01-17 01:47:19"}

The request was a next page of a List Filter.
When we retry the page request it then succeeds moments later. (2+ seconds delay)

**Comment by clement911** [comment] 2020-03-04 11:21
So this issue can be closed?

**Comment by Powellze** [comment] 2020-03-04 11:43
I would say not.
When paginating 649 pages with a limit of 100.
We get a 500 internal server error one in about every 30 pages.

This means the pagination when fetching 649 pages will create 20+ exceptions which result in failure of the 'next page', this never occurred in the old library as a 500 internal server error never occurred.

My point being, you expect the new V5 to result in a 500 error approximately every 30 page requests?
And to handle this, you have to wrap it in a try catch wait several seconds and manually retry? Thus wrapping failing code.

**Comment by clement911** [comment] 2020-03-04 12:25
Right, but internal Shopify errors have to be handled by Shopify, not ShopifySharp.
ShopifySharp is just a .Net client.

**Comment by joseph3114** [comment] 2020-03-04 13:05
I was getting the same periodic 500 error after updating, I kept trying different page sizes, and at a limit of 50 all of the 500 error ceased occurring.

**Comment by clement911** [comment] 2020-03-04 13:10
Interesting,  unfortunately for a 500, only Shopify could investigate the reason for the failure.

**Comment by Powellze** [comment] 2020-03-04 13:43
@joseph3114 Thank you for the heads up.
@clement911 any thoughts on best way to handle the 500/dig a bit deeper around the failure?
I know why they aren't sharing any detailed responses, and that i'm guessing is due to Security.

I will reach out to our partner to see if we can get a bit more information related to the failure.

**Comment by clement911** [comment] 2020-03-04 15:04
For a 500 only Shopify can help you. You can provide the request id to the support I think.

If you hear back from them, I'm curious to know what the problem is, and if it's related to how ShopifySharp calls the API or just an internal bug in Shopify.

**Comment by Powellze** [comment] 2020-03-04 15:12
Thanks Clement - Just waiting back on a response. Will share when I have more information.

**Comment by nozzlegear** [comment] 2020-03-04 17:47
Curiously I had a whole category of ShopifySharp's automated tests fail with 500 errors yesterday afternoon. Rerunning them a couple minutes later, everything passed. I wonder if Shopify is having some intermittent issues over the last 24 hours.

**Comment by Powellze** [comment] 2020-03-04 18:21
Interesting. I'm still waiting to hear back from Shopify regarding errors. For now i've caught and allowed it to retry - seems to be working okay (sticky plaster)

**Comment by nozzlegear** [comment] 2020-03-08 18:03
I'm going to assume this is an issue with Shopify for now, and close the issue. Let me know if you hear back from them and it still seems like a problem with the package!

**Closed by nozzlegear** 2020-03-08 18:03 UTC
Labels: question, upstream
