### ISSUE TITLE
Other limits can throw ShopifyRateLimitException

### ISSUE THREAD

**Issue by johnw-bluemark** [nozzlegear/ShopifySharp#455] opened 2020-02-21 01:12 UTC
The admin API rate limit is not the only limit that can throw a ShopifyRateLimitException. For example, the Shopify documentation says that development stores can only create 5 orders per minute (in practice, this appears to be 4 per minute). Exceeding this limit will return a 429 response code and throw a ShopifyRateLimitException. If you use the SmartRetryExecutionPolicy, it will result in spamming the Shopify servers with requests because it only cares about how full the bucket is, and has no knowledge of these other limits.

If the ShopifyRateLimitException had properties for bucket fill and bucket capacity, an exception handler would be able to tell when one of these other limits was hit. Alternatively, a new exception type for these other limits may be needed.

**Comment by nozzlegear** [comment] 2020-02-21 17:33
Yikes! That's definitely a problem, we don't want to be spamming Shopify's servers when we hit a dev store rate limit. 

@clement911 I think you wrote the Smart Retry policy, right? Do you have any ideas on how we might prevent this?

**Comment by clement911** [comment] 2020-02-23 09:48
@johnw-bluemark  does the 429 response include a Retry-After header?

See https://shopify.dev/concepts/about-apis/rate-limits#retry-after-header

If so, I could enhance the `SmartRetryExecutionPolicy` to detect this and waits the appropriate amount of time before retrying.

**Comment by clement911** [comment] 2020-02-23 14:04
I did some testing to trip the limit and there is a Retry-After header but without any value 😞.
We could bake in an exponential backoff policy in the `SmartRetryPolicy` or in a new policy.
However, given that this issue only affects dev stores, I'm hesitant to bake this into the library.

Have you considered using Polly to wrap your orderService.Create call in a retry policy?
See https://github.com/App-vNext/Polly#retry

**Comment by johnw-bluemark** [comment] 2020-02-24 18:38
I would prefer to use the available information on rate limits when possible, which means making use of the X-Shopify-Shop-Api-Call-Limit header. In addition to proper rate limiting, this information can be used to tell the difference between a 429 caused by hitting the rate limit, and a 429 caused by some other limit. However, this information isn't made available to my code, even if I use my own execution policy. If this information was included in the ShopifyRateLimitException or a different exception type was thrown if the bucket isn't full, that would be enough for my code to handle this case.

**Comment by clement911** [comment] 2020-02-24 18:51
X-Shopify-Shop-Api-Call-Limit is only relevant for leaky bucket limits but this is a different type of limit that is not exposed in headers afaik

**Comment by johnw-bluemark** [comment] 2020-02-25 18:43
Right. I know that is only relevant for the rate limit. But it's the only concrete information that is available, and it can be used to tell if the 429 is because of the rate limit or something else.  If the header says 40/40, then the rate limit was hit. If it says 2/40, then the 429 must have been caused by something else. I cannot respond appropriately to both limits if I don't know whether the 429 was caused by the rate limit or something else.

I'm suggesting that, when checking the 429 response and deciding to throw a ShopifyRateLimitException, either include the bucket fill info on the exception, or throw a different exception if the bucket is not full (ShopifyUnknownLimitException?). This way, my code will have some way of knowing whether the rate limit was hit, or a different one.

The new exception seems like the better idea to me, as I can just let the built-in SmartRetryExecutionPolicy handle the ShopifyRateLimitException, and my code can handle the new exception.

**Comment by clement911** [comment] 2020-02-26 07:27
I see what you mean now and that sounds like a pretty good idea!
I'll have a look at enhancing the `SmartRetryExecutionPolicy` to implement pretty much what you suggested.
Here is what I'm thinking.
`ShopifyRateLimitException` will get a new field Reason.
`public enum RateLimitReason { LeakyBucketEmpty, Other }`

If the reason is `Other`, then the policy will not attempt to retry and will throw instead.
In your code, you will be able to catch with 
`catch (ShopifyRateLimitException ex) when (ex.Reason == RateLimitReason.Other)`

Not sure exactly when I'll get to it as the current top priority is v5.0 but that shouldn't be too hard..

**Comment by johnw-bluemark** [comment] 2020-02-26 19:39
I was thinking something more like [this](https://github.com/johnw-bluemark/ShopifySharp/commit/6fda51bad3d92c38652b0f3beb1e423f88fbde61), with the BucketFill and BucketCapacity stored on the exception, but the enum would work too.

**Comment by clement911** [comment] 2020-02-27 12:26
I'm almost done with this.

One problem I'm facing is that the `X-Shopify-Shop-Api-Call-Limit` is **NOT** include if the 429 is caused by a full bucket.

So, this is the logic I'm using.

If 429 and `X-Shopify-Shop-Api-Call-Limit` present => non bucket breach.
If 429 and `X-Shopify-Shop-Api-Call-Limit` absent => bucket breach.

It works but I'm a bit worried to rely on this undocumented behavior.
What if tomorrow Shopify decides to always include this header, even for bucket breaches?
What if tomorrow Shopify doesn't include the header in non bucket breaches?

**Comment by clement911** [comment] 2020-02-27 12:30
https://community.shopify.com/c/Shopify-APIs-SDKs/Determine-if-HTTP-429-is-because-leaky-bucket-is-full-or-other/m-p/668792

**Comment by johnw-bluemark** [comment] 2020-02-27 19:22
That certainly complicates things. Ideally, we could convince Shopify to fix their code and include their headers more consistently, so that assumptions don't have to be made. Until then, all you can really do is act on the information that is available, and when it is missing, make assumptions based on current observed behavior. This means making the logic look like this:

If 429 and `X-Shopify-Shop-Api-Call-Limit` absent => bucket breach.
If 429 and `X-Shopify-Shop-Api-Call-Limit` present and BucketFill == BucketCapacity => bucket breach.
If 429 and `X-Shopify-Shop-Api-Call-Limit` present and BucketFill < BucketCapacity => non bucket breach.

It might break in the future if they stop including the header for other limits, but it wouldn't be any worse than it is now.

**Comment by clement911** [comment] 2020-03-02 11:53
See PR: https://github.com/nozzlegear/ShopifySharp/pull/466

**Comment by nozzlegear** [comment] 2020-03-02 20:07
PR merged, new behavior is now available in 5.0.1 on nuget. The old behavior can be re-enabled by passing `false` to the `SmartRetryExecutionPolicy` and `RetryExecutionPolicy` constructors. (#467)

**Closed by nozzlegear** 2020-03-02 20:07 UTC
Labels: bug, execution policy
