### ISSUE TITLE
Product CreateAsync error - expected Array to be a Hash at 

### ISSUE THREAD

**Issue by madushann** [nozzlegear/ShopifySharp#510] opened 2020-05-06 16:30 UTC
We have two shopify channels and one of them working fine and one failing to create products,
it timeout and give below error.

error: publications: expected Array to be a Hash at ShopifySharp.ShopifyService.CheckResponseExceptions(HttpResponseMessage response, String rawResponse) at ShopifySharp.ShopifyService.<>c__DisplayClass21_01.<<ExecuteRequestAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at ShopifySharp.SmartRetryExecutionPolicy.Run[T](CloneableRequestMessage baseRequest, ExecuteRequestAsync1 executeRequestAsync) at ShopifySharp.ShopifyService.ExecuteRequestAsync[T](RequestUri uri, HttpMethod method, HttpContent content, String rootElement) at ShopifySharp.ProductService.CreateAsync(Product product, ProductCreateOptions options)

do you have a clue on what could be the reason?

**Comment by nozzlegear** [comment] 2020-05-06 16:54
Hmm, sounds like it's expecting `publications` to be an object. Are you using the `publications` property in your code? On both channels?

**Comment by madushann** [comment] 2020-05-06 16:59
what is exactly about?
i checked the code we haven't used such a property. we use,

Basic product info (BodyHtml, Handle, vendor, Title, Tags, ProductTitle)
Metafields
Options
Images
Variants

**Comment by madushann** [comment] 2020-05-06 17:33
do you know a workaround for this, since I have total set of products waiting to be published to production till we find a solution?

**Comment by madushann** [comment] 2020-05-06 20:53
I really appreciate if you could give a hint on what could be done from my end to get through this

**Comment by nozzlegear** [comment] 2020-05-06 21:03
Could you show the code you're using to create the products? As far as I can tell there's no `Publications` property anywhere in this package, so I'm not able to reproduce the problem.

**Comment by madushann** [comment] 2020-05-06 21:49
Here is the code, I have just put them together to see easier. 
`            ProductService productService = new ProductService(channel.Host, secondary ? channel.SecondaryToken : channel.Token);
            productService.SetExecutionPolicy(new SmartRetryExecutionPolicy());

			Product shopifyProduct = new Product();
			
            shopifyProduct.BodyHtml = HttpUtility.HtmlDecode(dbProduct.Description);
            shopifyProduct.Handle = dbProduct.Handle;
            shopifyProduct.Vendor = Utils.GetPreferredVendorName(dataModel, dbProduct.Vendor.Trim());

            shopifyProduct.PublishedAt = DateTime.Now;

            shopifyProduct.Title = dbProduct.Title;
            shopifyProduct.Tags = string.Join(", ", dbProduct.Tags.Select(t => t.Tag));
            shopifyProduct.Tags += ",unknown-category";
            shopifyProduct.Tags += ",vendor:" + (Regex.Replace(shopifyProduct.Vendor.Replace(".", ""), @"[^A-Za-z0-9_\.~]+", "-")).ToLower();

            shopifyProduct.ProductType = "Sync";

            List<MetaField> metafields = new List<MetaField> { new MetaField { Namespace = "sync", Key = "sync_id", ValueType = "string", Value = dbProduct.Id.ToString() } };
			
            List<MarketplaceVariant> mpnVariants = dbProduct.Variants.Where(v => v.MPN != null && v.MPN != "").ToList();
            if (mpnVariants.Count > 0)
            {
                var mpn = mpnVariants[0].MPN;
                if (mpn != null && mpn != "")
                {
                    MetaField mpnMetafield = new MetaField { Namespace = "global", Key = "MPN", ValueType = "string", Value = mpn };
                    metafields.Add(mpnMetafield);
                }
            }

            if (!dbProduct.Feature1.IsNullOrEmpty())
            {
                MetaField productFeaturesMetafield = new MetaField { Namespace = "global", Key = "product_features", ValueType = "string", Value = FeatureConcat.All(dbProduct) };
                metafields.Add(productFeaturesMetafield);
            }

            shopifyProduct.Metafields = metafields;
			
			List<ProductOption> options = new List<ProductOption>();
            if (dbProduct.Option2 == null)
            {
                options = new List<ProductOption> { new ProductOption { Name = dbProduct.Option1 } };
            }
            else if (dbProduct.Option3 == null)
            {
                options = new List<ProductOption> { new ProductOption { Name = dbProduct.Option1 }, new ProductOption { Name = dbProduct.Option2 } };
            }
            else
            {
                options = new List<ProductOption> { new ProductOption { Name = dbProduct.Option1 }, new ProductOption { Name = dbProduct.Option2 }, new ProductOption { Name = dbProduct.Option3 } };
            }

            shopifyProduct.Options = options;
			
			List<ProductImage> images = new List<ProductImage>();
			
			images.Add(new ProductImage
			{
				Filename = GenerateImageFileName.Generate(dbImage.Handle, dbImage.FileExtension),
				Position = (int)dbImage.Position,
				Attachment = attachment,
				Alt = (dbImage.Variants.Count > 0 && dbImage.Variants.ElementAt(0).Title != "Default Title") ? dbImage.Variants.ElementAt(0).Title : dbImage.Product.Title
			});

			shopifyProduct.Images = images;
			
			List<ProductVariant> variants = new List<ProductVariant>();
			
			foreach (MarketplaceVariant variant in dbProduct.Variants.Where(v => v.Archived != true).OrderBy(s => s.Position))
            {
				ProductVariant v = new ProductVariant();

                v.Title = variant.Title;
				
               v.Price = (decimal?)VariantPriceCalculation.GetPrice(channel, variant); //(decimal)variant.Price;
                
				v.CompareAtPrice = (decimal)variant.CompareAtPrice;
                

                v.Option1 = variant.Option1;
				v.Option2 = variant.Option2;               
				v.Option3 = variant.Option3;                
                v.SKU = variant.SKU;
                v.Barcode = variant.Barcode;
                v.InventoryManagement = "shopify";
                v.InventoryPolicy = variant.AllowOOSSale == true ? "continue" : "deny";
                v.RequiresShipping = true;
                v.Taxable = true;
                v.Weight = variant.Weight != null ? (decimal)variant.Weight : 0;
                v.WeightUnit = variant.WeightUnit;

                v.Metafields = new List<MetaField> { new MetaField { Namespace = "syncdb", Key = "syncdb_id", ValueType = "string", Value = variant.Id.ToString() } };

                variants.Add(v);				
			}

			shopifyProduct.Variants = variants;
			
			shopifyProduct = await productService.CreateAsync(shopifyProduct);`

**Comment by nozzlegear** [comment] 2020-05-06 21:54
Thanks! I don't see anything crazy there but won't have a chance to run the code until this evening. Are you able to run and debug this code? If so, can you serialize the product to JSON using ShopifySharp's built-in serializer, and then check that JSON for any property named `publications`? It would be even better if you could paste the JSON here, assuming it doesn't contain any private or sensitive information.

```cs
var productJson = ShopifySharp.Infrastructure.Serializer.Serialize(shopifyProduct);

Console.WriteLine(productJson);
```

**Comment by nozzlegear** [comment] 2020-05-06 21:56
Ah hold, I may have found the issue as reported here on the Shopify forums: https://community.shopify.com/c/Shopify-APIs-SDKs/Bad-Request-publications-expected-Array-to-be-a-Hash/td-p/692222

It maybe that the sales channel that's failing hasn't been updated to use the 2020-01 version of the Shopify API, which is what ShopifySharp v5 is using. So it sounds like it may be sending incompatible properties.

**Comment by madushann** [comment] 2020-05-06 22:13
I am using bit older version of shopifysharp right now,
Assembly ShopifySharp, Version=4.19.1.0

I found the same thread earlier but i doubt because i saw you were using particular version of shopify API version in your shopifysharp versions so how it could change over time. may be i am missing something, correct me if i am wrong please. Also i have two different stores and one store works for the same product, I can publish. ill attach the json soon for better insight. 

appreciate you time.

**Comment by madushann** [comment] 2020-05-06 22:27
here you go,

`
{
	"title": "Booster Seat",
	"body_html": "<p>The Booster seat </p>",
	"published_at": "2020-05-06T17:18:22.9627344-05:00",
	"vendor": "ven! baby",
	"product_type": "Sync",
	"handle": "ven-baby-pug-baby-portable-booster-seat",
	"template_suffix": null,
	"published_scope": null,
	"tags": "ProductId: 45032a6b1606, seller:vendorbaby,unknown-category,vendor:vendorbaby",
	"variants": [
		{
			"product_id": null,
			"title": "Black",
			"sku": "HB6001",
			"position": null,
			"grams": null,
			"inventory_policy": "deny",
			"fulfillment_service": null,
			"inventory_item_id": null,
			"inventory_management": "shopify",
			"price": 49.99,
			"compare_at_price": 0.0,
			"option1": "Black",
			"option2": null,
			"option3": null,
			"taxable": true,
			"tax_code": null,
			"requires_shipping": true,
			"barcode": "85806103",
			"inventory_quantity": null,
			"old_inventory_quantity": null,
			"inventory_quantity_adjustment": null,
			"weight": 5.0,
			"weight_unit": "lb",
			"metafields": [
				{
					"created_at": null,
					"updated_at": null,
					"key": "syncdb_id",
					"value": "5e8aeba8-cea7-4f80-862f-d8f11153776c",//Guid changed to demostration
					"value_type": "string",
					"namespace": "sync",
					"description": null,
					"owner_id": null,
					"owner_resource": null,
					"id": null
				}
			],
			"id": null
		}
	],
	"options": [
		{
			"product_id": null,
			"name": "Color",
			"position": null,
			"values": null,
			"id": null
		}
	],
	"images": [
		{
			"product_id": null,
			"position": 1,
			"created_at": null,
			"updated_at": null,
			"src": null,
			"filename": "booster-seat-5e8aeba8-cea7-4f80-862f-d8f11153776c.png",//Guid changed to demostration
			"attachment": "iVBORw0KGgoAAAAN.....",
			"variant_ids": null,
			"height": null,
			"width": null,
			"alt": "Black",
			"metafields": null,
			"id": null
		}
	],
	"metafields": [
		{
			"created_at": null,
			"updated_at": null,
			"key": "syncdb_id",
			"value": "5e8aeba8-cea7-4f80-862f-d8f11153776c",//Guid changed to demostration
			"value_type": "string",
			"namespace": "syncdb",
			"description": null,
			"owner_id": null,
			"owner_resource": null,
			"id": null
		}
	],
	"id": null
}
`

**Comment by madushann** [comment] 2020-05-07 18:05
hope you will be able to find some time to look at this!

**Comment by madushann** [comment] 2020-05-07 21:24
more, my application is an azure function which is directly accessing shopify api thruogh shopifysharp to create products in shopify store. there no private app involve.

**Comment by nozzlegear** [comment] 2020-05-07 21:27
Could you try updating ShopifySharp and see if that helps? It would be best to update to version 5 or above as quickly as possible, but if that’s not feasible, you should be able to update to 4.25.3 without any refactoring needed. 

--
Josh Harms

**Comment by madushann** [comment] 2020-05-07 21:35
Thank you for the feedback, i'll first try 4.25.3. lets see how it goes. Thanks again.

**Comment by madushann** [comment] 2020-05-07 23:01
I did 4.25.3 but issue still remains and im going for latest version

**Comment by madushann** [comment] 2020-05-08 22:49
FYI,

I have tried with version upgrade to 4.25.3 as suggested which still gives the same error . then went with latest version and refactoring the code for new changes, it start giving different error which is more meaningful.

    "**Daily variant creation limit reached. Please try again later. See https://help.shopify.com/en/api/getting-started/api-call-limit for more information about rate limits and how to avoid them.**"

which seems the one of our apps is using more variant calls per day. so i am going to distribute the API calls to multiple days for one cycle. Now we process everyday so no of variant updates/creates daily.

**Comment by nozzlegear** [comment] 2020-05-14 20:47
Let me know if this is still an issue for you! I'll close this for now since it sounds like you might have fixed it.

**Closed by nozzlegear** 2020-05-14 20:47 UTC
Labels: missing or invalid properties
